services:
  # PostgreSQL 資料庫服務
  omochi-db:
    image: postgres:16-alpine
    container_name: omochi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"  # 對應 application-dev.yml
      POSTGRES_DB: omochikaeri
      TZ: Asia/Taipei
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql # 自動匯入 SQL

  # Redis 快取服務
  omochi-redis:
    image: redis:7-alpine
    container_name: omochi-redis
    restart: always
    command: redis-server --requirepass "123456" # 對應 application-dev.yml
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      TZ: Asia/Taipei