omochikaeri:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: omochikaeri
    username: postgres
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  awsoss:
    region: ap-northeast-1
    access-key-id: AKIAU6GDVQJZKY4GHKE5
    access-key-secret: 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
    bucket-name: omochikaeri-aws-bucket