server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${omochi.datasource.driver-class-name}
    url: jdbc:mysql://${omochi.datasource.host}:${omochi.datasource.port}/${omochi.datasource.database}?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: ${omochi.datasource.username}
    password: ${omochi.datasource.password}
  jackson:
    date-format:
      yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8

mybatis:
  #mapper設定檔
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kdhr.entity
  configuration:
    #開啟駝峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      omochi:
        mapper: debug
        service: info
        controller: info

omochi:
  jwt:
    # 設定jwt簽章加密時所使用的秘鑰
    admin-secret-key: itcast
    # 設定jwt過期時間
    admin-ttl: 7200000
    # 設定前端傳遞過來的令牌名稱
    admin-token-name: token